version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./strawberry
    steps:
      - checkout
      
workflows:
  main:
    jobs:
      - build-and-test
