version 2.1

orbs:
  python: circle/ci/python@0.3.8

jobs:
  build-strawberry:
    executor: python/default
    steps:
      - checkout
      - python/strawberry
      
workflows:
  main:
    jobs:
      - build-strawberry
